---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: mysql
  name: mysql-nodeport
  namespace: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30306
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  namespace: mysql
  name: mysql-clusterip
  labels:
    app: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
  ports:
    - name: tcp
      port: 3306
      protocol: TCP
